### ISSUE TITLE
LHError: PROTOCOL_TIMEOUT Internal Error

### ISSUE THREAD

**Issue by covalentbond** [erezrokah/netlify-plugin-is-website-vulnerable#134]
The following error happened in a build:

**UnhandledRejection**: a promise was rejected but not handled: LHError: PROTOCOL_TIMEOUT
_Plugin "netlify-plugin-is-website-vulnerable" internal error_

```
> 12:13:12 PM: Build ready to start
> 12:13:13 PM: build-image version: 3571f0130496395a23bffe9820bc78b4f73a6234
> 12:13:13 PM: build-image tag: v3.7.0
> 12:13:13 PM: buildbot version: c8ebd612d11de8df807ee80082ae1ebcb899414f
> 12:13:14 PM: Fetching cached dependencies
> 12:13:14 PM: Starting to download cache of 614.9MB
> 12:13:17 PM: Finished downloading cache in 3.75549561s
> 12:13:17 PM: Starting to extract cache
> 12:13:40 PM: Finished extracting cache in 22.889814292s
> 12:13:41 PM: Finished fetching cache in 27.019929066s
> 12:13:41 PM: Starting to prepare the repo for build
> 12:13:41 PM: Preparing Git Reference pull/121/head
> 12:13:44 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: '_site' versus '_site/' in the Netlify UI
> 12:13:45 PM: Starting build script
> 12:13:45 PM: Installing dependencies
> 12:13:45 PM: Python version set to 2.7
> 12:13:46 PM: Started restoring cached node version
> 12:13:53 PM: Finished restoring cached node version
> 12:13:54 PM: v10.24.0 is already installed.
> 12:13:55 PM: Now using node v10.24.0 (npm v6.14.11)
> 12:13:55 PM: Started restoring cached build plugins
> 12:13:55 PM: Finished restoring cached build plugins
> 12:13:55 PM: Attempting ruby version 2.6.2, read from environment
> 12:13:57 PM: Using ruby version 2.6.2
> 12:13:57 PM: Using bundler version 2.2.3 from Gemfile.lock
> 12:13:59 PM: Successfully installed bundler-2.2.3
> 12:13:59 PM: 1 gem installed
> 12:13:59 PM: Using PHP version 5.6
> 12:13:59 PM: Started restoring cached ruby gems
> 12:13:59 PM: Finished restoring cached ruby gems
> 12:13:59 PM: Installing pip dependencies
> 12:13:59 PM: Started restoring cached pip cache
> 12:13:59 PM: Finished restoring cached pip cache
> 12:13:59 PM: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
> 12:14:00 PM: Collecting ics>=0.7
> 12:14:00 PM:   Using cached ics-0.7-py2.py3-none-any.whl (42 kB)
> 12:14:00 PM: Collecting requests>=2.25.1
> 12:14:00 PM:   Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
> 12:14:00 PM: Collecting PyYAML>=5.4.1
> 12:14:00 PM:   Using cached PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl (574 kB)
> 12:14:00 PM: Collecting tatsu>4.2
> 12:14:00 PM:   Using cached TatSu-4.4.0-py2.py3-none-any.whl (85 kB)
> 12:14:00 PM: Collecting arrow<0.15,>=0.11
> 12:14:00 PM:   Using cached arrow-0.14.7-py2.py3-none-any.whl (39 kB)
> 12:14:00 PM: Requirement already satisfied: six>1.5 in /opt/buildhome/python2.7/lib/python2.7/site-packages (from ics>=0.7->-r requirements.txt (line 1)) (1.15.0)
> 12:14:01 PM: Collecting python-dateutil
> 12:14:01 PM:   Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
> 12:14:01 PM: Collecting chardet<5,>=3.0.2
> 12:14:01 PM:   Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
> 12:14:01 PM: Collecting urllib3<1.27,>=1.21.1
> 12:14:01 PM:   Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
> 12:14:01 PM: Collecting idna<3,>=2.5
> 12:14:01 PM:   Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
> 12:14:01 PM: Requirement already satisfied: certifi>=2017.4.17 in /opt/buildhome/python2.7/lib/python2.7/site-packages (from requests>=2.25.1->-r requirements.txt (line 2)) (2020.12.5)
> 12:14:01 PM: Collecting backports.functools-lru-cache>=1.2.1; python_version == "2.7"
> 12:14:01 PM:   Using cached backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl (5.7 kB)
> 12:14:01 PM: Installing collected packages: tatsu, backports.functools-lru-cache, python-dateutil, arrow, ics, chardet, urllib3, idna, requests, PyYAML
> 12:14:03 PM: Successfully installed PyYAML-5.4.1 arrow-0.14.7 backports.functools-lru-cache-1.6.1 chardet-4.0.0 ics-0.7 idna-2.10 python-dateutil-2.8.1 requests-2.25.1 tatsu-4.4.0 urllib3-1.26.4
> 12:14:03 PM: Pip dependencies installed
> 12:14:03 PM: Started restoring cached go cache
> 12:14:05 PM: Finished restoring cached go cache
> 12:14:05 PM: Installing Go version 1.12
> 12:14:05 PM: unset GOOS;
> 12:14:05 PM: unset GOARCH;
> 12:14:05 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64';
> 12:14:05 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64/bin:${PATH}";
> 12:14:05 PM: go version >&2;
> 12:14:05 PM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.12.linux.amd64.env';
> 12:14:05 PM: go version go1.12 linux/amd64
> 12:14:05 PM: Installing missing commands
> 12:14:05 PM: Verify run directory
> 12:14:07 PM: ​
> 12:14:07 PM: ────────────────────────────────────────────────────────────────
> 12:14:07 PM:   Netlify Build                                                 
> 12:14:07 PM: ────────────────────────────────────────────────────────────────
> 12:14:07 PM: ​
> 12:14:07 PM: ❯ Version
> 12:14:07 PM:   @netlify/build 9.10.2
> 12:14:07 PM: ​
> 12:14:07 PM: ❯ Flags
> 12:14:07 PM:   apiHost: api.netlify.com
> 12:14:07 PM:   cacheDir: /opt/build/cache
> 12:14:07 PM:   deployId: 6052f6805b4c730007a04f27
> 12:14:07 PM:   mode: buildbot
> 12:14:07 PM:   testOpts:
> 12:14:07 PM:     silentLingeringProcesses: ''
> 12:14:07 PM: ​
> 12:14:07 PM: ❯ Current directory
> 12:14:07 PM:   /opt/build/repo
> 12:14:07 PM: ​
> 12:14:07 PM: ❯ Config file
> 12:14:07 PM:   No config file was defined: using default values.
> 12:14:07 PM: ​
> 12:14:07 PM: ❯ Context
> 12:14:07 PM:   deploy-preview
> 12:14:07 PM: ​
> 12:14:07 PM: ❯ Loading plugins
> 12:14:07 PM:    - netlify-plugin-checklinks@4.1.1 from Netlify app
> 12:14:07 PM:    - netlify-plugin-is-website-vulnerable@1.0.10 from Netlify app
> 12:14:09 PM: ​
> 12:14:09 PM: ────────────────────────────────────────────────────────────────
> 12:14:09 PM:   1. Build command from Netlify app                             
> 12:14:09 PM: ────────────────────────────────────────────────────────────────
> 12:14:09 PM: ​
> 12:14:09 PM: $ jekyll build
> 12:14:10 PM: Configuration file: /opt/build/repo/_config.yml
> 12:14:11 PM:             Source: /opt/build/repo
> 12:14:11 PM:        Destination: /opt/build/repo/_site
> 12:14:11 PM:  Incremental build: disabled. Enable with --incremental
> 12:14:11 PM:       Generating...
> 12:14:11 PM:                     done in 0.359 seconds.
> 12:14:11 PM:  Auto-regeneration: disabled. Use --watch to enable.
> 12:14:11 PM: ​
> 12:14:11 PM: (build.command completed in 2.2s)
> 12:14:11 PM: ​
> 12:14:11 PM: ────────────────────────────────────────────────────────────────
> 12:14:11 PM:   2. onPostBuild command from netlify-plugin-checklinks         
> 12:14:11 PM: ────────────────────────────────────────────────────────────────
> 12:14:11 PM: ​
> 12:14:14 PM: ...................................................
> 12:14:14 PM:   51 tests
> 12:14:14 PM:   51 passed
> 12:14:14 PM: ​
> 12:14:14 PM: (netlify-plugin-checklinks onPostBuild completed in 3.3s)
> 12:14:14 PM: ​
> 12:14:14 PM: ────────────────────────────────────────────────────────────────────
> 12:14:14 PM:   3. onPostBuild command from netlify-plugin-is-website-vulnerable  
> 12:14:14 PM: ────────────────────────────────────────────────────────────────────
> 12:14:14 PM: ​
> 12:14:14 PM: Serving and scanning site from directory '_site'
> 12:14:17 PM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
> 12:14:17 PM: [DEP0066] 
> 12:14:17 PM:     at new module.exports (/opt/build/repo/.netlify/plugins/node_modules/union/lib/response-stream.js:50:60)
> 12:14:17 PM:     at new module.exports (/opt/build/repo/.netlify/plugins/node_modules/union/lib/routing-stream.js:30:17)
> 12:14:17 PM:     at Server.requestHandler (/opt/build/repo/.netlify/plugins/node_modules/union/lib/core.js:27:25)
> 12:14:17 PM:     at Server.emit (events.js:310:20)
> 12:14:17 PM:     at parserOnIncoming (_http_server.js:786:12)
> 12:14:17 PM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
> 12:15:33 PM: ​
> 12:15:33 PM: ────────────────────────────────────────────────────────────────
> 12:15:33 PM:   Plugin "netlify-plugin-is-website-vulnerable" internal error  
> 12:15:33 PM: ────────────────────────────────────────────────────────────────
> 12:15:33 PM: ​
> 12:15:33 PM:   Error message
> 12:15:33 PM:   UnhandledRejection: a promise was rejected but not handled: LHError: PROTOCOL_TIMEOUT
> 12:15:33 PM: ​
> 12:15:33 PM:   Plugin details
> 12:15:33 PM:   Package:        netlify-plugin-is-website-vulnerable
> 12:15:33 PM:   Version:        1.0.10
> 12:15:33 PM:   Repository:     git+https://github.com/erezrokah/netlify-plugin-is-website-vulnerable.git
> 12:15:33 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-is-website-vulnerable
> 12:15:33 PM:   Report issues:  https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/issues
> 12:15:33 PM: ​
> 12:15:33 PM:   Error location
> 12:15:33 PM:   In "onPostBuild" event in "netlify-plugin-is-website-vulnerable" from Netlify app
> 12:15:33 PM:       at Timeout._onTimeout (/opt/build/repo/.netlify/plugins/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)
> 12:15:33 PM:       at listOnTimeout (internal/timers.js:549:17)
> 12:15:33 PM:       at processTimers (internal/timers.js:492:7)
> 12:15:33 PM: ​
> 12:15:33 PM:   Error properties
> 12:15:33 PM:   {
> 12:15:33 PM:     code: 'PROTOCOL_TIMEOUT',
> 12:15:33 PM:     friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)',
> 12:15:33 PM:     lhrRuntimeError: true,
> 12:15:33 PM:     protocolMethod: 'Emulation.setScriptExecutionDisabled'
> 12:15:33 PM:   }
> 12:15:33 PM: ​
> 12:15:33 PM:   Resolved config
> 12:15:33 PM:   build:
> 12:15:33 PM:     command: jekyll build
> 12:15:33 PM:     commandOrigin: ui
> 12:15:33 PM:     environment:
> 12:15:33 PM:       - REVIEW_ID
> 12:15:33 PM:     publish: /opt/build/repo/_site
> 12:15:33 PM:   plugins:
> 12:15:33 PM:     - inputs: {}
> 12:15:33 PM:       origin: ui
> 12:15:33 PM:       package: netlify-plugin-checklinks
> 12:15:33 PM:     - inputs: {}
> 12:15:33 PM:       origin: ui
> 12:15:33 PM:       package: netlify-plugin-is-website-vulnerable
> 12:15:33 PM: Caching artifacts
> 12:15:33 PM: Started saving ruby gems
> 12:15:33 PM: Finished saving ruby gems
> 12:15:33 PM: Started saving build plugins
> 12:15:33 PM: Finished saving build plugins
> 12:15:33 PM: Started saving pip cache
> 12:15:33 PM: Finished saving pip cache
> 12:15:33 PM: Started saving emacs cask dependencies
> 12:15:33 PM: Finished saving emacs cask dependencies
> 12:15:33 PM: Started saving maven dependencies
> 12:15:33 PM: Finished saving maven dependencies
> 12:15:33 PM: Started saving boot dependencies
> 12:15:33 PM: Finished saving boot dependencies
> 12:15:33 PM: Started saving rust rustup cache
> 12:15:33 PM: Finished saving rust rustup cache
> 12:15:33 PM: Started saving go dependencies
> 12:15:35 PM: Finished saving go dependencies
> 12:15:35 PM: Build failed due to a plugin error: Build script returned non-zero exit code: 3
> 12:15:35 PM: Failing build: Failed to build site
> 12:15:35 PM: Failed during stage 'building site': Build script returned non-zero exit code: 3
> 12:15:35 PM: Finished processing build request in 2m21.883662912s
```

**Comment by erezrokah** [comment]
Hi @covalentbond, is this a reproducible bug? If so can you share a repo reproducing it?
There was [an incident yesterday](https://www.netlifystatus.com/incidents/5tj673z2zbwl) that might have contributed to this issue.

**Comment by covalentbond** [comment]
Hey sure! the most recent build failed log can be found [here](https://app.netlify.com/sites/condescending-dubinsky-4645a9/deploys/6052f6805b4c730007a04f27)
The repository can be find [here](https://github.com/zowe/zowe.github.io/pull/121)

**Comment by erezrokah** [comment]
Thanks @covalentbond I was able to reproduce https://app.netlify.com/sites/erez-zowe/deploys/60533a3b21ad63c1a9e85f9b.

Seems to be related to https://github.com/GoogleChrome/lighthouse/issues/6512#issuecomment-780805548

FYI, running locally via `netlify-cli` does seem to work (using `netlify build`).
