### ISSUE TITLE
`PROTOCOL_TIMEOUT` error

### ISSUE THREAD

**Issue by ehmicky** [erezrokah/netlify-plugin-is-website-vulnerable#8]
The following error happened in a build:

```
a promise was rejected but not handled: LHError: PROTOCOL_TIMEOUT 
    /opt/buildhome/.netlify-build-plugins/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21 Timeout._onTimeout
    internal/timers.js:549:17 listOnTimeout
    internal/timers.js:492:7 processTimers
```

[Bugsnag error](https://app.bugsnag.com/netlify/netlify-build/errors/5ed617fbce864d0018a6fd69).
This was a private repository.

Deploy logs:

```
11:06:59 AM: Build ready to start
11:07:01 AM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
11:07:01 AM: build-image tag: v3.3.14
11:07:01 AM: buildbot version: 80b5e22571e5cc4a3ded879ff356be5e92200072
11:07:02 AM: Fetching cached dependencies
11:07:02 AM: Starting to download cache of 487.3MB
11:07:16 AM: Finished downloading cache in 14.252390171s
11:07:16 AM: Starting to extract cache
11:07:36 AM: Finished extracting cache in 19.811682564s
11:07:36 AM: Finished fetching cache in 34.158098953s
11:07:36 AM: Starting to prepare the repo for build
11:07:37 AM: Preparing Git Reference pull/73/head
11:07:42 AM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
11:07:42 AM: Different functions path detected, going to use the one specified in the Netlify configuration file: '.functions' versus './.functions' in the Netlify UI
11:07:42 AM: Creating functions prep folder
11:07:42 AM: Starting build script
11:07:42 AM: Installing dependencies
11:07:43 AM: Started restoring cached node version
11:07:46 AM: Finished restoring cached node version
11:07:46 AM: Attempting node version 'lts/dubnium' from .nvmrc
11:07:46 AM: v10.20.1 is already installed.
11:07:47 AM: Now using node v10.20.1 (npm v6.14.4)
11:07:47 AM: Started restoring cached build plugins
11:07:47 AM: Finished restoring cached build plugins
11:07:47 AM: Attempting ruby version 2.6.2, read from environment
11:07:49 AM: Using ruby version 2.6.2
11:07:49 AM: Using PHP version 5.6
11:07:49 AM: 5.2 is already installed.
11:07:49 AM: Using Swift version 5.2
11:07:49 AM: Started restoring cached node modules
11:07:49 AM: Finished restoring cached node modules
11:07:49 AM: Started restoring cached yarn cache
11:07:49 AM: Finished restoring cached yarn cache
11:07:50 AM: Installing NPM modules using Yarn version 1.17.3
11:07:51 AM: yarn install v1.17.3
11:07:51 AM: [1/4] Resolving packages...
11:07:52 AM: [2/4] Fetching packages...
11:08:31 AM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
11:08:31 AM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
11:08:31 AM: info fsevents@1.2.12: The platform "linux" is incompatible with this module.
11:08:31 AM: info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
11:08:31 AM: [3/4] Linking dependencies...
11:08:32 AM: warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.1" has incorrect peer dependency "react-refresh@^0.8.2".
11:08:32 AM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
11:08:32 AM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
11:08:32 AM: warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
11:08:32 AM: warning " > gatsby-remark-prismjs@3.4.1" has unmet peer dependency "prismjs@^1.15.0".
11:08:32 AM: warning " > lodash-webpack-plugin@0.11.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
11:08:32 AM: warning "netlify-cms-app > netlify-cms-widget-code@1.1.4" has unmet peer dependency "codemirror@^5.46.0".
11:08:32 AM: warning "netlify-cms-app > netlify-cms-core > react-hot-loader@4.12.20" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
11:08:32 AM: warning "netlify-cms-app > netlify-cms-widget-code > react-codemirror2@6.0.1" has unmet peer dependency "codemirror@5.x".
11:08:32 AM: warning "netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
11:08:32 AM: warning " > react-elastic-carousel@0.4.1" has incorrect peer dependency "styled-components@^5.1.0".
11:08:32 AM: warning " > uglifyjs-webpack-plugin@2.2.0" has unmet peer dependency "webpack@^4.0.0".
11:09:08 AM: [4/4] Building fresh packages...
11:09:18 AM: $ netlify-lambda install
11:09:19 AM: netlify-lambda: installing function dependencies
11:09:19 AM: Done in 88.45s.
11:09:19 AM: NPM modules installed using Yarn
11:09:19 AM: Started restoring cached go cache
11:09:19 AM: Finished restoring cached go cache
11:09:19 AM: go version go1.12 linux/amd64
11:09:19 AM: go version go1.12 linux/amd64
11:09:19 AM: Installing missing commands
11:09:19 AM: Verify run directory
11:09:21 AM: ​
11:09:21 AM: ┌─────────────────────────────┐
11:09:21 AM: │        Netlify Build        │
11:09:21 AM: └─────────────────────────────┘
11:09:21 AM: ​
11:09:21 AM: ❯ Version
11:09:21 AM:   @netlify/build 1.0.14
11:09:21 AM: ​
11:09:21 AM: ❯ Flags
11:09:21 AM:   mode: buildbot
11:09:21 AM: ​
11:09:21 AM: ❯ Current directory
11:09:21 AM:   /opt/build/repo
11:09:21 AM: ​
11:09:21 AM: ❯ Config file
11:09:21 AM:   /opt/build/repo/netlify.toml
11:09:21 AM: ​
11:09:21 AM: ❯ Context
11:09:21 AM:   deploy-preview
11:09:22 AM: ​
11:09:22 AM: ❯ Loading plugins
11:09:22 AM:    - @netlify/plugin-functions-core@1.0.14 from core
11:09:22 AM:    - netlify-plugin-is-website-vulnerable@1.0.8 from Netlify app
11:09:24 AM: ​
11:09:24 AM: ┌────────────────────────────────────┐
11:09:24 AM: │ 1. build.command from netlify.toml │
11:09:24 AM: └────────────────────────────────────┘
11:09:24 AM: ​
11:09:24 AM: $ npm run prod
11:09:24 AM: > ppe4nyc@2.1.2 prod /opt/build/repo
11:09:24 AM: > npm run build; npm run build:lambda
11:09:24 AM: > ppe4nyc@2.1.2 build /opt/build/repo
11:09:24 AM: > gatsby build
11:09:27 AM: success open and validate gatsby-configs - 0.110s
11:09:29 AM: success load plugins - 1.614s
11:09:29 AM: success onPreInit - 0.013s
11:09:29 AM: 
11:09:29 AM: success delete html and css files from previous builds - 0.015s
11:09:29 AM: 
11:09:29 AM: success initialize cache - 0.009s
11:09:29 AM: 
11:09:29 AM: success copy gatsby files - 0.046s
11:09:29 AM: success onPreBootstrap - 0.010s
11:09:29 AM: 
11:09:29 AM: success createSchemaCustomization - 0.191s
11:09:30 AM: success source and transform nodes - 0.733s
11:09:30 AM: 
11:09:30 AM: success building schema - 0.446s
11:09:31 AM: success createPages - 0.200s
11:09:31 AM: success createPagesStatefully - 0.121s
11:09:31 AM: 
11:09:31 AM: success onPreExtractQueries - 0.000s
11:09:31 AM: success update schema - 0.036s
11:09:32 AM: success extract queries from components - 0.898s
11:09:32 AM: success write out requires - 0.005s
11:09:32 AM: success write out redirect data - 0.001s
11:09:32 AM: success Build manifest and related icons - 0.001s
11:09:32 AM: success onPostBootstrap - 0.002s
11:09:32 AM: ⠀
11:09:32 AM: 
11:09:32 AM: info bootstrap finished - 7.249s
11:09:32 AM: 
11:09:32 AM: ⠀
11:10:53 AM: 
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/assets/sass/styles.sass
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/AboutPageTemplate/index.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/ProfileCards/index.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/components/Share/styles.sass
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-article-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-pages-donate-success-index-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./node_modules/@brainhubeu/react-carousel/lib/style.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-ppe-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM: 
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/assets/sass/styles.sass (1)
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/AboutPageTemplate/index.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/ProfileCards/index.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/components/Share/styles.sass
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-article-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-pages-donate-success-index-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./node_modules/@brainhubeu/react-carousel/lib/style.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-ppe-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/ProfileCards/index.css
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/Footer/index.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/NavBar/Header.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/assets/sass/styles.sass (2)
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-about-page-js
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/assets/sass/styles.sass (2)
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/components/Share/styles.sass
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-article-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-pages-donate-success-index-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./node_modules/@brainhubeu/react-carousel/lib/style.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-ppe-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/NavBar/Header.css
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/components/Share/styles.sass
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-article-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-pages-donate-success-index-js
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./node_modules/@brainhubeu/react-carousel/lib/style.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-ppe-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-1-3!./src/components/Share/styles.sass
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/Footer/index.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-pages-donate-success-index-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-article-page-js
11:10:53 AM: warning chunk styles [mini-css-extract-plugin]
11:10:53 AM: Conflicting order. Following module has been added:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/Footer/index.css
11:10:53 AM: despite it was not able to fulfill desired ordering with these modules:
11:10:53 AM:  * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./node_modules/@brainhubeu/react-carousel/lib/style.css
11:10:53 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-ppe-page-js
11:10:53 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-info-page-js
11:10:53 AM: success Building production JavaScript and CSS bundles - 81.279s
11:10:53 AM: 
11:10:53 AM: success Rewriting compilation hashes - 0.003s
11:10:54 AM: 
11:10:54 AM: success run queries - 81.904s - 28/28 0.34/s
11:11:02 AM: 
11:11:02 AM: 
11:11:02 AM: success Building static HTML for pages - 7.836s - 28/28 3.57/s
11:11:02 AM: info Generated public/sw.js, which will precache 8 files, totaling 425886 bytes.
11:11:02 AM: The following pages will be precached:
11:11:02 AM: /offline-plugin-app-shell-fallback/index.html
11:11:02 AM: 
11:11:02 AM: success onPostBuild - 0.227s
11:11:02 AM: 
11:11:02 AM: info Done building in 97.248 sec
11:11:02 AM: > ppe4nyc@2.1.2 build:lambda /opt/build/repo
11:11:02 AM: > netlify-lambda build functions
11:11:03 AM: netlify-lambda: Building functions
11:11:06 AM: Hash: 5765bfdfc6ca0a129f1e
11:11:06 AM: Version: webpack 4.42.1
11:11:06 AM: Time: 2471ms
11:11:06 AM: Built at: 06/02/2020 9:11:06 AM
11:11:06 AM:            Asset      Size  Chunks             Chunk Names
11:11:06 AM: stripe-charge.js  53.8 KiB       0  [emitted]  stripe-charge
11:11:06 AM: Entrypoint stripe-charge = stripe-charge.js
11:11:06 AM:  [0] ../node_modules/stripe/lib/StripeResource.js 15.5 KiB {0} [built]
11:11:06 AM:  [1] ../node_modules/stripe/lib/utils.js 11.2 KiB {0} [built]
11:11:06 AM:  [2] ../node_modules/stripe/lib/Error.js 4.47 KiB {0} [built]
11:11:06 AM:  [4] ../node_modules/stripe/lib/resources/Accounts.js 2.93 KiB {0} [built]
11:11:06 AM:  [5] external "path" 42 bytes {0} [built]
11:11:06 AM:  [6] external "events" 42 bytes {0} [built]
11:11:06 AM:  [8] external "crypto" 42 bytes {0} [built]
11:11:06 AM:  [9] ../node_modules/stripe/lib/StripeMethod.js 1.58 KiB {0} [built]
11:11:06 AM: [11] ../node_modules/stripe/lib/Webhooks.js 4.52 KiB {0} [built]
11:11:06 AM: [12] ../node_modules/stripe/lib/stripe.js 13.1 KiB {0} [built]
11:11:06 AM: [13] ./stripe-charge.js 2.04 KiB {0} [built]
11:11:06 AM: [14] ../node_modules/stripe/lib/resources.js 3.42 KiB {0} [built]
11:11:06 AM: [81] ../node_modules/stripe/package.json 1.82 KiB {0} [built]
11:11:06 AM: [82] ../node_modules/dotenv/lib/main.js 2.93 KiB {0} [built]
11:11:06 AM: [83] external "fs" 42 bytes {0} [built]
11:11:06 AM:     + 69 hidden modules
11:11:06 AM: ​
11:11:06 AM: (build.command completed in 1m 42.1s)
11:11:06 AM: ​
11:11:06 AM: ┌────────────────────────────────────────────────────────────┐
11:11:06 AM: │ 2. onPostBuild command from @netlify/plugin-functions-core │
11:11:06 AM: └────────────────────────────────────────────────────────────┘
11:11:06 AM: ​
11:11:06 AM: Packaging functions from .functions
11:11:06 AM: Functions packaged in /tmp/zisi-5ed616b3ca8ac6000919bc57
11:11:06 AM:  - stripe-charge.zip
11:11:06 AM: ​
11:11:06 AM: (@netlify/plugin-functions-core onPostBuild completed in 521ms)
11:11:06 AM: ​
11:11:06 AM: ┌────────────────────────────────────────────────────────────────┐
11:11:06 AM: │ 3. onSuccess command from netlify-plugin-is-website-vulnerable │
11:11:06 AM: └────────────────────────────────────────────────────────────────┘
11:11:06 AM: ​
11:11:06 AM: Serving and scanning site from directory 'public'
11:11:10 AM:  ⚠  warning (DeprecationWarning)  OutgoingMessage.prototype._headers is deprecated
11:11:10 AM: [DEP0066] 
11:11:10 AM:     at new module.exports (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/response-stream.js:50:60)
11:11:10 AM:     at new module.exports (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/routing-stream.js:30:17)
11:11:10 AM:     at Server.requestHandler (/opt/buildhome/.netlify-build-plugins/node_modules/union/lib/core.js:27:25)
11:11:10 AM:     at Server.emit (events.js:310:20)
11:11:10 AM:     at parserOnIncoming (_http_server.js:786:12)
11:11:10 AM:     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
11:12:27 AM: ​
11:12:27 AM: ┌──────────────────────────────────────────────────────────────┐
11:12:27 AM: │ Plugin "netlify-plugin-is-website-vulnerable" internal error │
11:12:27 AM: └──────────────────────────────────────────────────────────────┘
11:12:27 AM: ​
11:12:27 AM:   Error message
11:12:27 AM:   UnhandledRejection: a promise was rejected but not handled: LHError: PROTOCOL_TIMEOUT
11:12:27 AM: ​
11:12:27 AM:   Plugin details
11:12:27 AM:   Package:        netlify-plugin-is-website-vulnerable
11:12:27 AM:   Version:        1.0.8
11:12:27 AM:   Repository:     git+https://github.com/erezrokah/netlify-plugin-is-website-vulnerable.git
11:12:27 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-is-website-vulnerable
11:12:27 AM:   Report issues:  https://github.com/erezrokah/netlify-plugin-is-website-vulnerable/issues
11:12:27 AM: ​
11:12:27 AM:   Error location
11:12:27 AM:   In "onSuccess" event in "netlify-plugin-is-website-vulnerable" from Netlify app
11:12:27 AM:       at Timeout._onTimeout (/opt/buildhome/.netlify-build-plugins/node_modules/is-website-vulnerable/node_modules/lighthouse/lighthouse-core/gather/driver.js:352:21)
11:12:27 AM:       at listOnTimeout (internal/timers.js:549:17)
11:12:27 AM:       at processTimers (internal/timers.js:492:7)
11:12:27 AM: ​
11:12:27 AM:   Error properties
11:12:27 AM:   {
11:12:27 AM:     code: 'PROTOCOL_TIMEOUT',
11:12:27 AM:     friendlyMessage: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)',
11:12:27 AM:     lhrRuntimeError: true,
11:12:27 AM:     protocolMethod: 'Emulation.setScriptExecutionDisabled'
11:12:27 AM:   }
11:12:27 AM: ​
11:12:27 AM:   Resolved config
11:12:27 AM:   build:
11:12:27 AM:     command: npm run prod
11:12:27 AM:     functions: /opt/build/repo/.functions
11:12:27 AM:     publish: /opt/build/repo/public
11:12:27 AM:   headers:
11:12:27 AM:     - for: /*
11:12:27 AM:       values:
11:12:27 AM:         Access-Control-Allow-Origin: '*'
11:12:27 AM:   plugins:
11:12:27 AM:     - inputs: {}
11:12:27 AM:       origin: ui
11:12:27 AM:       package: netlify-plugin-is-website-vulnerable
11:12:27 AM:   redirects:
11:12:27 AM:     - from: /*
11:12:27 AM:       status: 200
11:12:27 AM:       to: /index.html
11:12:27 AM: Caching artifacts
11:12:27 AM: Started saving node modules
11:12:27 AM: Finished saving node modules
11:12:27 AM: Started saving build plugins
11:12:27 AM: Finished saving build plugins
11:12:27 AM: Started saving yarn cache
11:12:27 AM: Finished saving yarn cache
11:12:27 AM: Started saving pip cache
11:12:27 AM: Finished saving pip cache
11:12:27 AM: Started saving emacs cask dependencies
11:12:27 AM: Finished saving emacs cask dependencies
11:12:27 AM: Started saving maven dependencies
11:12:27 AM: Finished saving maven dependencies
11:12:27 AM: Started saving boot dependencies
11:12:27 AM: Finished saving boot dependencies
11:12:27 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
11:12:27 AM: Started saving go dependencies
11:12:27 AM: Finished saving go dependencies
11:12:27 AM: 
11:12:27 AM: ** WARNING **
11:12:27 AM: There are some lingering processes even after the build process finished:
11:12:27 AM: USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
11:12:27 AM: buildbot    1715  0.0  0.1 466820 50724 ?        S    09:11   0:00 /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-is-website-vulnerable/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome --type=zygote --no-zygote-sandbox --no-sandbox --headless --headless
11:12:27 AM: buildbot    1716  0.0  0.1 466820 51128 ?        S    09:11   0:00 /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-is-website-vulnerable/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome --type=zygote --no-sandbox --headless --headless
11:12:27 AM: buildbot    1729  0.1  0.1 525084 49100 ?        Sl   09:11   0:00 /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-is-website-vulnerable/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome --type=gpu-process --field-trial-handle=13544110577853321973,7834875859872545398,131072 --disable-features=TranslateUI --no-sandbox --headless --headless --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA= --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --shared-files
11:12:27 AM: buildbot    1737  0.4  0.2 550300 70156 ?        Sl   09:11   0:00 /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-is-website-vulnerable/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome --type=utility --field-trial-handle=13544110577853321973,7834875859872545398,131072 --disable-features=TranslateUI --lang=en-US --service-sandbox-type=network --no-sandbox --use-gl=swiftshader-webgl --mute-audio --headless --shared-files
11:12:27 AM: buildbot    1738  0.0  0.2 4778164 65192 ?       Sl   09:11   0:00 /opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-is-website-vulnerable/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome --type=renderer --no-sandbox --allow-pre-commit-input --disable-background-timer-throttling --file-url-path-alias=/gen=/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-is-website-vulnerable/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/gen --remote-debugging-port=35059 --field-trial-handle=13544110577853321973,7834875859872545398,131072 --disable-features=TranslateUI --disable-gpu-compositing --lang=en-US --headless --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --shared-files
11:12:27 AM: Our builds do not kill your processes automatically, so please make sure
11:12:27 AM: that nothing is running after your build finishes, or it will be marked as
11:12:27 AM: failed since something is still running.
11:12:27 AM: 
11:12:27 AM: Error running command: Build script returned non-zero exit code: 1
11:12:27 AM: Failing build: Failed to build site
11:12:27 AM: Finished processing build request in 5m26.084800941s
```

Do you know what the error might be?

**Comment by erezrokah** [comment]
I'm guessing something went wrong with serving the static site and lighthouse can't access it.
This looks like a Gatsby build (which I tested the plugin and it works with https://github.com/netlify-templates/gatsby-starter-netlify-cms), so not sure exactly what is happening.
Linking https://github.com/GoogleChrome/lighthouse/issues/6512 for context
